In [61]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import re
import shutil
import string
import tensorflow as tf
import keras

from tensorflow.keras import layers
from tensorflow.keras import losses

import matplotlib.pyplot as plt

In [62]:
import mydata as md

data = md.Data('cache')


In [70]:
import pymystem3
mystem = pymystem3.Mystem()

In [3]:
raw_train_ds, raw_valid_ds, raw_test_ds = data.load('tabiturient')

In [19]:
df = pd.read_csv('/home/alex/Data/datasets/RuTweetCorp/negative.csv')

In [20]:
len(df)

111923

In [19]:
vi = list(raw_valid_ds.as_numpy_iterator())

In [24]:
si = list(raw_test_ds.as_numpy_iterator())

In [20]:
ti = list(raw_train_ds.as_numpy_iterator())

In [23]:
len(vi)

2876

In [26]:
c=0
for j in range(len(si)):
    for i in range(len(vi)):
        if vi[i][0] == si[j][0] and i!=j:
            c=c+1
            print(f"ti[{i}]==si[{j}]")
print(c)

0


In [26]:
all_data = pd.read_json("/home/alex/Data/datasets/tabiturient/all-reviews.jsonl", lines=True)

In [29]:
sr = str(sr, 'utf-8')

In [40]:
sr

'я учиться в политех на 1 курс ипмм. учиться непросто, но весело, обо все по порядок:\n\n1) общежитие в целое оставлять положительный впечатление. на кухня нет очередь, но место грязноватый(зависеть только от проживать), в душ очередь не бывать вообще, в прачечная иногда приходиться занимать место, чистота в туалет также зависеть только от проживать. стоить сказать, что убирать каждый  будний день, поэтому в целое чисто. довольно много таракан, но их кол-во зависеть от чистоплотность вы и ваш сосед. недалеко пятерочка, аптека и все необходимый. самый главное - 15 минута до политех.\n\n2) первый время очень тяжело, все новый, непривычный. очень сильно помогать адаптер: рассказывать про вуз, студенческий жизнь, преподаватель и отвечать на любой вопрос, организовывать встреча.\n\n3) в политех очень развитый внеучебный деятельность, можно находить занятие на любой вкус. развитый студклуб, в он постоянно проходить мероприятие. также студсовет устраивать мероприятие прямо в общежитие почти к

In [30]:
all_data

id                                            content  \
0        7  Пишу про Герцена. В этом ВУЗе существует одна ...   
1        9  Наверняка многие абитуриенты с Иркутской облас...   
2       10  В этом ВУЗе Вас не научат ничему. Преподавател...   
3       11  Учусь в Ранхигс на одном из лучших и старейших...   
4       12  Учусь на 3 курсе одного из лучших факультетов....   
...    ...                                                ...   
3633  8416  Я выбрала именно Президентскую академию, потом...   
3634  8417  Престижный и высокорейтинговый вуз, который пр...   
3635  8418  Здравствуйте! Хочу поделиться своим опытом обу...   
3636  8419  Учусь в технологическом университете на третье...   
3637  8420  Писать долгие и скучные предложения не буду, т...   

                               parent_url label_name  label  
0      https://tabiturient.ru/vuzu/herzen        Bad      0  
1         https://tabiturient.ru/vuzu/isu        Bad      0  
2                                    None        Bad      0  
3      https://tabiturient.ru/vuzu/ranepa    Neutral      1  
4     https://tabiturient.ru/vuzu/voenmeh        Bad      0  
...                                   ...        ...    ...  
3633   https://tabiturient.ru/vuzu/ranepa       Good      2  
3634  https://tabiturient.ru/vuzu/voenmeh       Good      2  
3635                                 None       Good      2  
3636    https://tabiturient.ru/vuzu/vsuet       Good      2  
3637    https://tabiturient.ru/vuzu/vsuet       Good      2  

[3638 rows x 5 columns]

In [37]:
all_text[all_text['content'] == sr]

KeyError: 'content'

In [34]:
all_text = all_data['content']

In [35]:
all_text = all_text.map(data.lemmatize)

In [41]:
for row in np.array(all_text):
    if row == sr:
        print(row)


я учиться в политех на 1 курс ипмм. учиться непросто, но весело, обо все по порядок:

1) общежитие в целое оставлять положительный впечатление. на кухня нет очередь, но место грязноватый(зависеть только от проживать), в душ очередь не бывать вообще, в прачечная иногда приходиться занимать место, чистота в туалет также зависеть только от проживать. стоить сказать, что убирать каждый  будний день, поэтому в целое чисто. довольно много таракан, но их кол-во зависеть от чистоплотность вы и ваш сосед. недалеко пятерочка, аптека и все необходимый. самый главное - 15 минута до политех.

2) первый время очень тяжело, все новый, непривычный. очень сильно помогать адаптер: рассказывать про вуз, студенческий жизнь, преподаватель и отвечать на любой вопрос, организовывать встреча.

3) в политех очень развитый внеучебный деятельность, можно находить занятие на любой вкус. развитый студклуб, в он постоянно проходить мероприятие. также студсовет устраивать мероприятие прямо в общежитие почти каждый н

In [102]:
f1macro = tf.keras.metrics.F1Score(average='macro')

In [103]:
f1micro = tf.keras.metrics.F1Score(average='micro')

In [123]:
f1w= tf.keras.metrics.F1Score(average='weighted')

In [104]:
f1 = tf.keras.metrics.F1Score()

In [105]:
precision = tf.keras.metrics.Precision()

In [106]:
recall = tf.keras.metrics.Recall()

In [107]:
acc = tf.keras.metrics.CategoricalAccuracy()

In [108]:
d0=[[1,0],[1,0],[1,0],[1,0],[1,0],[1,0],[1,0],[1,0],[0,1],[0,1]]

In [109]:
d1=[[1,0],[1,0],[1,0],[1,0],[1,0],[1,0],[1,0],[1,0],[1,0],[1,0]]

In [110]:
d2=[[1,0],[1,0],[1,0],[1,0],[0,1],[0,1],[0,1],[0,1],[0,1],[1,0]]

In [112]:
acc.reset_state()
acc.update_state(d0,d1)
acc.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.8>

In [127]:
f1.reset_state()
f1.update_state(d0,d1)
f1.result()

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.8888889, 0.       ], dtype=float32)>

In [117]:
precision.reset_state()
precision.update_state(d0,d2)
precision.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [60]:
recall.reset_state()
recall.update_state(d0,d2)
recall.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.4>

In [125]:
f1w.reset_state()
f1w.update_state(d0,d1)
f1w.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.7111111>

In [63]:
max_features = 100
sequence_length = 10

vectorize_layer = keras.layers.TextVectorization(
    max_tokens=max_features,
    output_mode='int',
    output_sequence_length=sequence_length
)

In [64]:
vectorize_layer.adapt('Это случилось в час невероятно жаркого заката')

In [37]:
vectorize_layer([['Это', 'случилось'], ['Час','жаркого', 'заката']])

ValueError: Exception encountered when calling TextVectorization.call().

Can't convert non-rectangular Python sequence to Tensor.

Arguments received by TextVectorization.call():
  • inputs=[["'Это'", "'случилось'"], ["'Час'", "'жаркого'", "'заката'"]]

In [74]:
mystem.analyze('Это случилось: в час невероятно жаркого заката')

[{'analysis': [{'lex': 'это',
    'wt': 0.7809833731,
    'gr': 'SPRO,ед,сред,неод=(вин|им)'}],
  'text': 'Это'},
 {'text': ' '},
 {'analysis': [{'lex': 'случаться',
    'wt': 1,
    'gr': 'V,нп=прош,ед,изъяв,сред,сов'}],
  'text': 'случилось'},
 {'text': ': '},
 {'analysis': [{'lex': 'в', 'wt': 0.9999917878, 'gr': 'PR='}], 'text': 'в'},
 {'text': ' '},
 {'analysis': [{'lex': 'час', 'wt': 1, 'gr': 'S,муж,неод=(вин,ед|им,ед)'}],
  'text': 'час'},
 {'text': ' '},
 {'analysis': [{'lex': 'невероятно', 'wt': 0.8008481654, 'gr': 'ADV='}],
  'text': 'невероятно'},
 {'text': ' '},
 {'analysis': [{'lex': 'жаркий',
    'wt': 0.7113804921,
    'gr': 'A=(вин,ед,полн,муж,од|род,ед,полн,муж|род,ед,полн,сред)'}],
  'text': 'жаркого'},
 {'text': ' '},
 {'analysis': [{'lex': 'закат', 'wt': 1, 'gr': 'S,муж,неод=род,ед'}],
  'text': 'заката'},
 {'text': '\n'}]

In [75]:
import datetime

In [76]:
d = datetime.datetime.now()

In [77]:
d

datetime.datetime(2024, 6, 8, 11, 10, 41, 914589)

In [81]:
d.strftime("%Y-%m-%d %H:%M:%S")

'2024-06-08 11:10:41'

In [90]:
NAME = 'NAME'
log_dir = f"logs/fit-{NAME}/{datetime.datetime.now().strftime("%Y-%m-%d %H-%M-%S")}"


log_dir

'logs/fit-NAME/2024-06-08 11-18-25'

In [92]:
df = pd.read_json('/home/alex/Data/datasets/tabiturient/unique-reviews.jsonl', lines=True)

In [93]:
dfl = np.array(df['label'])

In [94]:
call = len(dfl)

In [95]:
call

3595

In [96]:
c0 = len(dfl[df['label']==0])

In [97]:
c0

1792

In [98]:
c1 = len(dfl[df['label']==1])

In [99]:
c2 = len(dfl[df['label']==2])

In [101]:
print(c0/call,c1/call,c2/call)

0.4984700973574409 0.18915159944367177 0.3123783031988873
